export { MarketPage } from "./MarketPage";
export { MainPage } from "./MainPage";
export { WalletPage } from "./WalletPage";
export { GoldenLeague } from "./GoldenLeague";
export { YourFriends } from "./YourFriends";
export { FarmingCoins } from "./FarmingCoins";
export { BoostsSelect } from "./BoostsSelect";
export { PartyKings } from "./PartyKings";
export { YesCoin } from "./YesCoin";
