export const ROUTES = {
  MAIN_BOARD: '/',
  CRYPTO_HOLDER: '/crypto-holder',
  TRADE_MARKET: '/trade-market',
  LEAGUES: '/leagues',
  YOUR_FRIENDS: '/your-friends',
  FARM_COINS: '/farm-coins',
  GAME_BOOST: '/game-boost',
  PARTY_KINGS: '/party-kings',
  YES_COIN: '/yes-coin',
  ENTER_SQUAD: '/enter-squad',
  SQUAD_NAME: '/squad-name',
  JOIN_SQUAD: '/join-squad',
  SQUAD_WORK: '/squad-work',
  MAJOR_DIGITS: '/major-digits',
}
