/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * YesCoin-API
 * OpenAPI spec version: 0.1.0
 */
import type { LeagueRead } from './leagueRead'
import type { SquadReadDetailRate } from './squadReadDetailRate'
import type { SquadReadDetailUsers } from './squadReadDetailUsers'

export interface SquadReadDetail {
  balance: number
  group: string
  league: LeagueRead
  name: string
  rate: SquadReadDetailRate
  users: SquadReadDetailUsers
}
