/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * YesCoin-API
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateBalance } from './userUpdateBalance';

export interface UserUpdate {
  balance: UserUpdateBalance;
  telegram_id: number;
}
