/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * YesCoin-API
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadIsPremium } from './userReadIsPremium'
import type { UserReadLanguageCode } from './userReadLanguageCode'
import type { UserReadRate } from './userReadRate'

export interface UserRead {
  balance: number
  energy: number
  invite_code: string
  is_premium: UserReadIsPremium
  language_code: UserReadLanguageCode
  rate: UserReadRate
  telegram_id: number
  total_score: number
  username: string
}
