/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * YesCoin-API
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadDetailIsPremium } from './userReadDetailIsPremium'
import type { UserReadDetailLanguageCode } from './userReadDetailLanguageCode'
import type { LeagueRead } from './leagueRead'
import type { UserReadDetailRate } from './userReadDetailRate'
import type { UserReadDetailSquad } from './userReadDetailSquad'

export interface UserReadDetail {
  balance: number
  created_at: string
  energy: number
  invite_code: string
  is_premium: UserReadDetailIsPremium
  language_code: UserReadDetailLanguageCode
  league: LeagueRead
  rate: UserReadDetailRate
  squad: UserReadDetailSquad
  telegram_id: number
  total_score: number
  updated_at: string
  username: string
}
